### ISSUE TITLE
Linked users that shouldn't be

### ISSUE THREAD

**Issue by Butalabs** [FullLifeGames/Showdown-Replay-Scouter#1]
Hey FullLifeGames! I noticed a few issues in this project while making researches today.

When I search "leru | gen7monotype" as smogon user, I get replays for the user "soma", but those 2 are different persons.

Same with "vodoom | gen7monotype" as smogon user, I shouldn't get replays for "miyoka".

I hope these can help fixing some issues, otherwise the app is amazing !

**Comment by FullLifeGames** [comment]
Well the thing is that the application finds the currect users and it finds a certain number of non correct users with the Smogon users depending on if the person you are searching the replays for has posted replays of another user previously.

Therefore I cannot fix this.
