### ISSUE TITLE
Grouping replays

### ISSUE THREAD

**Issue by bkiint** [FullLifeGames/Showdown-Replay-Scouter#22]
Hey FullLifeGames! Currently replays are grouped together if they have the same six pokemon. This can be problematic in tiers with only a handful of viable pokemon. Could you consider adding a toggle to group / ungroup replays based on user input. Really enjoy using the app :D

**Comment by FullLifeGames** [comment]
Done with https://github.com/FullLifeGames/Showdown-Replay-Scouter/commit/c654a42a8ae40168ac54681f6e2a89c36b7d81d0
